import numpy as np
import pandas as pd

def read_dft():
    """
    Read the data frame dft generated by test_gprob_rbf in testRbfsacob.py
    """
    dft = pd.read_feather("feather/dft.feather")
    print(dft.loc[dft['degree']==1, ['gprob', 'kernel', 'degree', 'seed', 'inter', 'err']])
    print(dft.loc[dft['degree']==2, ['gprob', 'kernel', 'degree', 'seed', 'inter', 'err']])
    err2 = np.array(dft.loc[dft['degree']==2, ['err']])
    assert np.allclose(err2,0, atol=1e-6)
    dummy = 0


read_dft()
